package org.kethereum.rpc

val ETHEREUM_NETWORK_MAIN = "main"
val ETHEREUM_NETWORK_RINKEBY = "rinkeby"
val ETHEREUM_NETWORK_ROPSTEN = "ropsten"

val ETHEREUM_NETWORKS = listOf(
        ETHEREUM_NETWORK_MAIN,
        ETHEREUM_NETWORK_RINKEBY,
        ETHEREUM_NETWORK_ROPSTEN
)